ccflags-y += -I$(srctree)/techpack/camera/include/uapi
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_smmu/
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_core

obj-$(CONFIG_SPECTRA_CAMERA) += zte_cam_eeprom_dev.o zte_cam_eeprom_core.o zte_cam_eeprom_soc.o
obj-$(CONFIG_SPECTRA_CAMERA) += s5k3t1sp_front_eeprom.o s5k3t1sp_aux_eeprom.o s5k3t1sp_front_sm7250_eeprom.o hi846_sm7250_eeprom.o s5kgw1sp_sm7250_eeprom.o ov32a1q_front_eeprom.o ov48b2q_eeprom.o hi846_sm6350_eeprom.o hi846_front_sm6350_eeprom.o gc8034_front_sm6350_eeprom.o hi1634_sm6350_eeprom.o s5kgw3sp_sm7250_eeprom.o s5kgh1sp_sm7250_eeprom.o hi846_wide_sm7250_eeprom.o
